### ISSUE TITLE
Upate README.md file with the code bellow

### ISSUE THREAD

**Issue by chgasparoto** [chgasparoto/terraform-aws-glue#1]
<pre>
# AWS Glue Terraform module

Terraform module which creates Glue resources on AWS.

These types of resources are supported:

* [Catalog Dabatase](https://www.terraform.io/docs/providers/aws/r/glue_catalog_database.html)
* [Catalog Table](https://www.terraform.io/docs/providers/aws/r/glue_catalog_table.html)
* [Connection](https://www.terraform.io/docs/providers/aws/r/glue_connection.html)
* [Crawler](https://www.terraform.io/docs/providers/aws/r/glue_crawler.html)
* [Job](https://www.terraform.io/docs/providers/aws/r/glue_job.html)
* [Trigger](https://www.terraform.io/docs/providers/aws/r/glue_trigger.html)

## Usage

```hcl
module "glue" {
}
```

## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|:----:|:-----:|:-----:|

## Outputs

| Name | Description |
|------|-------------|

## Authors

Module managed by [Cleber Gasparoto](https://github.com/chgasparoto) and [Mateus Perdigão](https://github.com/Perdiga)

## License
</pre>

**Comment by danhenriquesc** [comment]
https://github.com/chgasparoto/terraform-aws-glue/pull/2

**Comment by chgasparoto** [comment]
Thanks!
